# Tried using this with the following package section in pixi.toml

# [package]

# [package.build]
# backend = { name = "pixi-build-rattler-build", version = ">=0.3.5,<1" }

context:
  version: "0.1.0"

build:
  noarch: python

source:
  path: ../

outputs:
  - package:
      name: pkoffee-base
      version: ${{ version }}
    build: 
      number: 0
      script:
        - uv pip install --python "$PREFIX/bin/python" -vv --no-deps --no-build-isolation .
    requirements:
      host:
        - python >=3.12,<3.15
        - uv
      run:
        - bidict >=0.23.1,<1
        - numpy >=2.3.5,<3
        - pandas >=2.3.3,<3
        - python >=3.12,<3.15
        - scipy >=1.16.3,<2
        - tomlkit >=0.13.3,<1

    tests:
      - python:
          imports:
            - pkoffee
      - script:
        - pkoffee analyze --help
  
  - package: 
      name: pkoffee
      version: ${{ version }}
    requirements:
      run:
        - ${{ pin_subpackage('pkoffee-base', exact=True) }}
        - matplotlib-base >=3.10.8,<4
        - seaborn >=0.13.2,<0.14
    tests:
      - python:
          imports:
            - pkoffee.visualization
      - script:
        - pkoffee visualize --help

about:
  homepage: https://github.com/s3-school/pkoffee-solution
  license: MIT
  license_file: LICENSE
  summary: S3School Pkoffe example package
  description: |
    Demonstrate how to implement a conda python package using pixi
  documentation: https://github.com/s3-school/pkoffee-solution/blob/main/README.md